# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mikhalchankasm.OfficeLiveMCP
PackageVersion: 0.4.2
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Office Live MCP version 0.4.2
  Publisher: mikhalchankasm
  ProductCode: '{47C3867B-C095-4C76-AACD-DA6A268CF854}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mikhalchankasm/office-live-mcp/releases/download/v0.4.2/office-live-mcp-0.4.2-setup.exe
  InstallerSha256: 59BFC5B71632437ACD72EC10D8F8CE5805A87BBE73807F06DD4DF83B880699D6
ManifestType: installer
ManifestVersion: 1.12.0
