# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mikhalchankasm.OfficeLiveMCP
PackageVersion: 0.4.4
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-06
AppsAndFeaturesEntries:
- DisplayName: Office Live MCP version 0.4.4
  Publisher: mikhalchankasm
  ProductCode: '{47C3867B-C095-4C76-AACD-DA6A268CF854}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/mikhalchankasm/office-live-mcp/releases/download/v0.4.4/office-live-mcp-0.4.4-setup.exe
  InstallerSha256: 7F2D549B0D62FFB445B36880EA3B84969381537BB4D80076B5936815B7D58034
ManifestType: installer
ManifestVersion: 1.12.0
